
TOPDIR	:= ..

include ${TOPDIR}/make.rules

CONFFILES = $(wildcard *.conf)

all:
	@echo "do all nothing"

clean:
	@echo "do clean nothing"

cleanall:
	@echo "do cleanall nothing"

install:
	cp -rf ${CONFFILES} ${INSTALL_PATH}/conf

uninstall:
	@echo "do uninstall nothing"

touch:
	@echo "do touch nothing"