
#-----------------------------------------------------------------------

APP       := DemoApp
TARGET    := DemoServer
MFLAGS    :=
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

INCLUDE   += -I/usr/local/mqq/wbl/include 
LIB       += -L/usr/local/mqq/wbl/lib -lwbl

#-----------------------------------------------------------------------

include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------
